---
title: "Files"
output:
  rmarkdown::html_vignette:
    toc: true
description: |
  Files Uploads.
vignette: >
  %\VignetteIndexEntry{Datasets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo = FALSE, message =  FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
Sys.unsetenv('EDP_PROFILE')
```

# Uploads

## CSV

```{r csv}
library(quartzbio.edp)
Sys.setenv(EDP_PROFILE = "vsim-dev_rw")
v <- Vault_create('_vignettes',  description = 'quartzbio.edp vignettes',  tags = list('please_removed'))
src_dir <- Folder_create(vault_id = v, 'src')
irisp <- file.path(tempdir(), 'iris.csv')
write.csv(iris[1:10,], irisp, row.names=FALSE)
vpath <- 'v1/iris_10.csv'
fi <- File_upload(v, irisp, vpath )
fi$path
fi$mimetype

# all columns have been imported into text
File_query(fi, filters= filters('Sepal.Length = 4.7'))

File_query(fi, filters= filters('Sepal.Width contains ".4"'))

```

## JSON


```{r json}
irisj <- file.path(tempdir(), 'iris.json')
jsonlite::write_json(iris[1:10, ], irisj) 

vpath <- 'v1/iris_10.json'
fi2 <- File_upload(v, irisj, vpath)

fi2$path
fi2$mimetype

# Column
#File_query(fi2, filters= filters('Sepal.Length = 4.6'))
#File_query(fi2)
#Object.query(fi2$id, 'Sepal.Length__gt 5')
#Object.query(fi2$id, 'Sepal.Length__eq 4.6')

```
# Downloads

```{r down-csv2}
lp <- file.path(tempdir(), 'iris_down.csv')
File_download(fi,lp)
read.csv(lp, ) %>% head(2)
delete(v)
```
