---
title: "Vaults, Files, Datasets and Objects"
output: rmarkdown::html_vignette

description: |
  describe Vaults, Files, Datasets and other EDP objects.
vignette: >
  %\VignetteIndexEntry{Vaults, Files, Datasets and Objects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# User

```{r}
library(quartzbio.edp)
# select an EDP instance using a profile
Sys.getenv('EDP_PROFILE')
Sys.setenv(EDP_PROFILE = 'vsim-dev_rw')
Sys.getenv('EDP_PROFILE')
# fetch current user info
get_connection()
u <- User()
u$first_name
u$last_name
u$full_name
u$id
u$email
u$account$name
u$url

```


# Vaults

```{r}
library(quartzbio.edp)
# select an EDP instance using a profile
Sys.setenv(EDP_PROFILE = 'vsim-dev_rw')
# fetch personnal vault info
myV <- Vault()
# personal vault: user-id
myV$name
myV$full_path 
myV$has_children  
myV$has_folder_children
myV$user$full_name
myV$permissions
```

## Vault creation




```{r, include = FALSE, echp = FALSE, message = FALSE,warning = FALSE }
Sys.unsetenv('EDP_PROFILE')
```




